---
abstract: 'RSS feed monitor for Bot::Cobalt'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-Plugin-RSS
provides:
  Bot::Cobalt::Plugin::RSS:
    file: lib/Bot/Cobalt/Plugin/RSS.pm
    version: 0.002
  Bot::Cobalt::Plugin::RSS::Conf:
    file: lib/Bot/Cobalt/Plugin/RSS/Conf.pm
    version: 0
requires:
  Bot::Cobalt: 0.003
  File::Spec: 0
  XML::RSS::Feed: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
